-- =============================================================================
-- DATABASE SCHEMA: HỆ THỐNG QUẢN LÝ CHUỖI CỬA HÀNG THUỐC TÂY (ORACLE DB)
-- =============================================================================

-- 0. XÓA BẢNG CŨ
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIGITAL_SIGNATURES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GOODS_RECEIPT_ITEMS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GOODS_RECEIPTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUPPLIERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INVENTORY_TRANSACTIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INVOICE_ITEMS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INVOICES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INVENTORIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DRUG_BATCHES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DRUGS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ROLES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BRANCHES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 1. BẢNG CHI NHÁNH
CREATE TABLE BRANCHES (
    id          VARCHAR2(50)     NOT NULL,
    BranchName  VARCHAR2(255)    NOT NULL,
    Address     VARCHAR2(500),
    CONSTRAINT PK_BRANCHES PRIMARY KEY (id)
);

-- 2. BẢNG VAI TRÒ
CREATE TABLE ROLES (
    id          VARCHAR2(50)     NOT NULL,
    RoleName    VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK_ROLES PRIMARY KEY (id),
    CONSTRAINT UQ_ROLES_NAME UNIQUE (RoleName)
);

-- 3. BẢNG NGƯỜI DÙNG
CREATE TABLE USERS (
    id           VARCHAR2(50)    NOT NULL,
    Username     VARCHAR2(100)   NOT NULL,
    PasswordHash VARCHAR2(255)   NOT NULL,
    RoleId       VARCHAR2(50)    NOT NULL,
    BranchId     VARCHAR2(50)    NOT NULL,
    IsActive     NUMBER(1)       DEFAULT 1 NOT NULL CHECK (IsActive IN (0, 1)),
    CONSTRAINT PK_USERS PRIMARY KEY (id),
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (Username),
    CONSTRAINT FK_USERS_ROLES FOREIGN KEY (RoleId) REFERENCES ROLES(id),
    CONSTRAINT FK_USERS_BRANCHES FOREIGN KEY (BranchId) REFERENCES BRANCHES(id)
);

-- 4. BẢNG DANH MỤC THUỐC
CREATE TABLE DRUGS (
    id               VARCHAR2(50)     NOT NULL,
    DrugCode         VARCHAR2(50)     NOT NULL,
    Name             VARCHAR2(255)    NOT NULL,
    ActiveIngredient VARCHAR2(255),
    Unit             VARCHAR2(50)     NOT NULL,
    Price            NUMBER(15, 2)    NOT NULL CHECK (Price >= 0),
    IsActive         NUMBER(1)        DEFAULT 1 NOT NULL CHECK (IsActive IN (0, 1)),
    CreatedDate      TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_DRUGS PRIMARY KEY (id),
    CONSTRAINT UQ_DRUGS_CODE UNIQUE (DrugCode)
);

-- 5. BẢNG LÔ THUỐC
CREATE TABLE DRUG_BATCHES (
    id         VARCHAR2(50)    NOT NULL,
    DrugId     VARCHAR2(50)    NOT NULL,
    BatchNo    VARCHAR2(100)   NOT NULL,
    MfgDate    DATE,
    ExpiryDate DATE            NOT NULL,
    CONSTRAINT PK_DRUG_BATCHES PRIMARY KEY (id),
    CONSTRAINT FK_BATCHES_DRUGS FOREIGN KEY (DrugId) REFERENCES DRUGS(id)
);

-- 6. BẢNG TỒN KHO
CREATE TABLE INVENTORIES (
    BranchId VARCHAR2(50) NOT NULL,
    DrugId   VARCHAR2(50) NOT NULL,
    BatchId  VARCHAR2(50) NOT NULL,
    Quantity NUMBER(10)   DEFAULT 0 NOT NULL CHECK (Quantity >= 0),
    CONSTRAINT PK_INVENTORIES PRIMARY KEY (BranchId, DrugId, BatchId),
    CONSTRAINT FK_INV_BRANCHES FOREIGN KEY (BranchId) REFERENCES BRANCHES(id),
    CONSTRAINT FK_INV_DRUGS FOREIGN KEY (DrugId) REFERENCES DRUGS(id),
    CONSTRAINT FK_INV_BATCHES FOREIGN KEY (BatchId) REFERENCES DRUG_BATCHES(id)
);

-- 7. BẢNG HÓA ĐƠN BÁN HÀNG
CREATE TABLE INVOICES (
    id          VARCHAR2(50)    NOT NULL,
    InvoiceNo   VARCHAR2(50)    NOT NULL,
    CreatedDate TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TotalAmount NUMBER(15, 2)   DEFAULT 0.00 NOT NULL CHECK (TotalAmount >= 0),
    BranchId    VARCHAR2(50)    NOT NULL,
    CashierId   VARCHAR2(50)    NOT NULL,
    CONSTRAINT PK_INVOICES PRIMARY KEY (id),
    CONSTRAINT UQ_INVOICES_NO UNIQUE (InvoiceNo),
    CONSTRAINT FK_INVOICES_BRANCHES FOREIGN KEY (BranchId) REFERENCES BRANCHES(id),
    CONSTRAINT FK_INVOICES_CASHIER FOREIGN KEY (CashierId) REFERENCES USERS(id)
);

-- 8. BẢNG CHI TIẾT HÓA ĐƠN
CREATE TABLE INVOICE_ITEMS (
    InvoiceId VARCHAR2(50)    NOT NULL,
    DrugId    VARCHAR2(50)    NOT NULL,
    BatchId   VARCHAR2(50)    NOT NULL,
    Quantity  NUMBER(10)      NOT NULL CHECK (Quantity > 0),
    UnitPrice NUMBER(15, 2)   NOT NULL CHECK (UnitPrice >= 0),
    SubTotal  NUMBER(15, 2)   NOT NULL CHECK (SubTotal >= 0),
    CONSTRAINT PK_INVOICE_ITEMS PRIMARY KEY (InvoiceId, DrugId, BatchId),
    CONSTRAINT FK_ITEMS_INVOICES FOREIGN KEY (InvoiceId) REFERENCES INVOICES(id),
    CONSTRAINT FK_ITEMS_DRUGS FOREIGN KEY (DrugId) REFERENCES DRUGS(id),
    CONSTRAINT FK_ITEMS_BATCHES FOREIGN KEY (BatchId) REFERENCES DRUG_BATCHES(id)
);

-- 9. BẢNG CHỮ KÝ SỐ HÓA ĐƠN
CREATE TABLE DIGITAL_SIGNATURES (
    id               VARCHAR2(50)   NOT NULL,
    InvoiceId        VARCHAR2(50)   NOT NULL,
    HashValue_SHA256 VARCHAR2(255)  NOT NULL,
    SignatureData    CLOB           NOT NULL,
    CertSerial       VARCHAR2(100)  NOT NULL,
    SignedAt         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIGITAL_SIGNATURES PRIMARY KEY (id),
    CONSTRAINT UQ_SIGNATURE_INVOICE UNIQUE (InvoiceId),
    CONSTRAINT FK_SIGNATURE_INVOICES FOREIGN KEY (InvoiceId) REFERENCES INVOICES(id)
);

-- 10. BẢNG LỊCH SỬ BIẾN ĐỘNG TỒN KHO
CREATE TABLE INVENTORY_TRANSACTIONS (
    id                VARCHAR2(50)     NOT NULL,
    BranchId          VARCHAR2(50)     NOT NULL,
    DrugId            VARCHAR2(50)     NOT NULL,
    BatchId           VARCHAR2(50)     NOT NULL,
    TransactionType   VARCHAR2(20)     NOT NULL CHECK (TransactionType IN ('NHAP', 'XUAT_BAN', 'DIEU_CHINH', 'TRA_HANG')),
    QuantityChange    NUMBER(10)       NOT NULL,
    RemainingQuantity NUMBER(10)       NOT NULL CHECK (RemainingQuantity >= 0),
    CreatedBy         VARCHAR2(50)     NOT NULL,
    CreatedDate       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Note              VARCHAR2(500),
    CONSTRAINT PK_INV_TRANSACTIONS PRIMARY KEY (id),
    CONSTRAINT FK_INV_TX_BRANCHES FOREIGN KEY (BranchId) REFERENCES BRANCHES(id),
    CONSTRAINT FK_INV_TX_DRUGS FOREIGN KEY (DrugId) REFERENCES DRUGS(id),
    CONSTRAINT FK_INV_TX_BATCHES FOREIGN KEY (BatchId) REFERENCES DRUG_BATCHES(id),
    CONSTRAINT FK_INV_TX_USERS FOREIGN KEY (CreatedBy) REFERENCES USERS(id)
);

-- 11. BẢNG NHÀ CUNG CẤP (SUPPLIERS)
CREATE TABLE SUPPLIERS (
    id            VARCHAR2(50)     NOT NULL,
    SupplierCode  VARCHAR2(50)     NOT NULL,
    SupplierName  VARCHAR2(255)    NOT NULL,
    ContactPerson VARCHAR2(100),
    PhoneNumber   VARCHAR2(20),
    Email         VARCHAR2(100),
    Address       VARCHAR2(500),
    TaxCode       VARCHAR2(50),
    IsActive      NUMBER(1)        DEFAULT 1 NOT NULL CHECK (IsActive IN (0, 1)),
    CreatedDate   TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SUPPLIERS PRIMARY KEY (id),
    CONSTRAINT UQ_SUPPLIERS_CODE UNIQUE (SupplierCode)
);

-- 12. BẢNG PHIẾU NHẬP KHO (GOODS_RECEIPTS)
CREATE TABLE GOODS_RECEIPTS (
    id                VARCHAR2(50)     NOT NULL,
    ReceiptNo         VARCHAR2(50)     NOT NULL,
    BranchId          VARCHAR2(50)     NOT NULL,
    SupplierId        VARCHAR2(50)     NOT NULL,
    WarehouseStaffId  VARCHAR2(50)     NOT NULL,
    TotalAmount       NUMBER(15, 2)    DEFAULT 0.00 NOT NULL CHECK (TotalAmount >= 0),
    Note              VARCHAR2(500),
    Status            VARCHAR2(50)     DEFAULT 'COMPLETED' NOT NULL CHECK (Status IN ('COMPLETED', 'CANCELLED')),
    CreatedDate       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_GOODS_RECEIPTS PRIMARY KEY (id),
    CONSTRAINT UQ_GOODS_RECEIPTS_NO UNIQUE (ReceiptNo),
    CONSTRAINT FK_RECEIPTS_BRANCHES FOREIGN KEY (BranchId) REFERENCES BRANCHES(id),
    CONSTRAINT FK_RECEIPTS_SUPPLIERS FOREIGN KEY (SupplierId) REFERENCES SUPPLIERS(id),
    CONSTRAINT FK_RECEIPTS_USERS FOREIGN KEY (WarehouseStaffId) REFERENCES USERS(id)
);

-- 13. BẢNG CHI TIẾT PHIẾU NHẬP KHO (GOODS_RECEIPT_ITEMS)
CREATE TABLE GOODS_RECEIPT_ITEMS (
    id           VARCHAR2(50)     NOT NULL,
    ReceiptId    VARCHAR2(50)     NOT NULL,
    DrugId       VARCHAR2(50)     NOT NULL,
    BatchId      VARCHAR2(50)     NOT NULL,
    BatchNo      VARCHAR2(100)    NOT NULL,
    ExpiryDate   DATE             NOT NULL,
    Quantity     NUMBER(10)       NOT NULL CHECK (Quantity > 0),
    ImportPrice  NUMBER(15, 2)    NOT NULL CHECK (ImportPrice >= 0),
    SubTotal     NUMBER(15, 2)    NOT NULL CHECK (SubTotal >= 0),
    CONSTRAINT PK_GOODS_RECEIPT_ITEMS PRIMARY KEY (id),
    CONSTRAINT FK_RECEIPT_ITEMS_RECEIPTS FOREIGN KEY (ReceiptId) REFERENCES GOODS_RECEIPTS(id),
    CONSTRAINT FK_RECEIPT_ITEMS_DRUGS FOREIGN KEY (DrugId) REFERENCES DRUGS(id),
    CONSTRAINT FK_RECEIPT_ITEMS_BATCHES FOREIGN KEY (BatchId) REFERENCES DRUG_BATCHES(id)
);

-- CHỈ MỤC (INDEXES)
CREATE INDEX IDX_USERS_BRANCH ON USERS(BranchId);
CREATE INDEX IDX_INVOICES_BRANCH ON INVOICES(BranchId);
CREATE INDEX IDX_INVENTORIES_BRANCH ON INVENTORIES(BranchId);
CREATE INDEX IDX_INVOICES_CREATED_DATE ON INVOICES(CreatedDate);
CREATE INDEX IDX_BATCHES_EXPIRY ON DRUG_BATCHES(ExpiryDate);
CREATE INDEX IDX_BATCHES_DRUG ON DRUG_BATCHES(DrugId);
CREATE INDEX IDX_INVOICE_ITEMS_INVOICE ON INVOICE_ITEMS(InvoiceId);
CREATE INDEX IDX_INV_TX_BRANCH ON INVENTORY_TRANSACTIONS(BranchId);
CREATE INDEX IDX_INV_TX_DRUG_BATCH ON INVENTORY_TRANSACTIONS(BranchId, DrugId, BatchId);
CREATE INDEX IDX_INV_TX_DATE ON INVENTORY_TRANSACTIONS(CreatedDate);
CREATE INDEX IDX_RECEIPTS_BRANCH ON GOODS_RECEIPTS(BranchId);
CREATE INDEX IDX_RECEIPTS_SUPPLIER ON GOODS_RECEIPTS(SupplierId);
CREATE INDEX IDX_RECEIPTS_DATE ON GOODS_RECEIPTS(CreatedDate);
CREATE INDEX IDX_RECEIPT_ITEMS_RECEIPT ON GOODS_RECEIPT_ITEMS(ReceiptId);
CREATE INDEX IDX_RECEIPT_ITEMS_DRUG ON GOODS_RECEIPT_ITEMS(DrugId);
CREATE INDEX IDX_DRUGS_NAME ON DRUGS(Name);
CREATE INDEX IDX_DRUGS_ACTIVE ON DRUGS(IsActive);