<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PharmaSecure.Application</RootNamespace>
    <AssemblyName>PharmaSecure.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PharmaSecure.Domain\PharmaSecure.Domain.csproj" />
  </ItemGroup>

</Project>
